var tableauQuestion = [
    {   question : "Pouvez vous tirée en centre ville sans raison ?:",
        propositionA : "OUI je suis sur GTAV",
        propositionB : "Non c'est pas autorisée",
        propositionC : "Si la ville c'est de la merde oui",
        propositionD : "C'est mon pote qui a commencé",
        reponse : "B"},
		
    {   question : "Avez vous le droit de braquée une arme sur qui que ce soit ?:",
        propositionA : "Oui je suis Lucky Luke",
        propositionB : "Non, j'encoure une peine",
        propositionC : "pour chassée les rats",
        propositionD : "Un petit chat de temps en temps",
        reponse : "B"},
		
    {   question : "Avez le droit de sortir une arme en pleine rue ?",
        propositionA : "Oui la ville est déserte",
        propositionB : "Oui si la personne en face présente une menace",
        propositionC : "Non y'a des caméras",
        propositionD : "Seulement pour impressionner les filles",
        reponse : "B"},
	
	{   question : "Qu'est-ce que la légitime défense ?:",
        propositionA : "Se défendre proportionnellement à l'attaque",
        propositionB : "C'est avoir le droit de tirée",
        propositionC : "C'est savoir tirée",
        propositionD : "Oeil pour oeil, dent pour dent",
        reponse : "A"},
		
	{   question : "Connaissez vous les risque d'une arme ?",
        propositionA : "C'est dangereux",
        propositionB : "C'est dure à utilisée",
        propositionC : "Bah y'a pas de risque",
        propositionD : "La réponse D",
        reponse : "A"},
]
